#include "ADC.h"


void ADC_config (void)
{
	//PA0:INPUT ANALOG
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER0;//ANALOG MODE
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPDR0;//
	
	//ADC1->CFGR2 &= ~ADC_CFGR2_CKMODE;//ADCCLK (Asynchronous clock mode), generated at product level (refer to RCC section)
	//RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	//RCC->CFGR |= RCC_CFGR_ADCPRE_DIV6;
	
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN; /* (1) */
	RCC->CR2 |= RCC_CR2_HSI14ON; /* (2) */
	while ((RCC->CR2 & RCC_CR2_HSI14RDY) == 0); /* (3) */
	
	ADC1->CFGR1 |= ADC_CFGR1_CONT;//CONTINUOS CONVERSION(1)
	ADC1->CFGR1 |= ADC_CFGR1_SCANDIR; /* (2) */
	ADC1->CHSELR = ADC_CHSELR_CHSEL0; /* (3) */
	ADC1->SMPR |= ADC_SMPR_SMP_0 | ADC_SMPR_SMP_1 | ADC_SMPR_SMP_2; /* (4) */
	//ADC1->IER = ADC_IER_EOCIE | ADC_IER_EOSEQIE | ADC_IER_OVRIE; /* (5) */
	ADC->CCR |= ADC_CCR_VREFEN; /* (6) */
	
	ADC1->CR |= ADC_CR_ADSTART;
		
	ADC1->CR |= ADC_CR_ADEN;
}
